FROM node:latest as builder

RUN mkdir /app
WORKDIR /app
COPY ./ ./

RUN wget -qO- https://get.pnpm.io/install.sh | ENV="~/.shrc" SHELL="$(which sh)" sh -

RUN pnpm install
RUN pnpm build

FROM caddy:latest

RUN mkdir /app
WORKDIR /app
COPY --from=builder /app/dist /app/

EXPOSE 80
EXPOSE 443
CMD caddy file_server --domain hegemonies.site --root /app
