name: deploy to production

on: [push]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - name: deploy to prod
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOSTNAME }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: ./deploy-hegemonies-site-v5.sh ${{ github.ref_name }}
