name: deploy to production

on: [push]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - name: install deps
        run: pnpm install
      - name: build
        run: pnpm build
      - name: build docker image
        run: pnpm build-docker
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: push docker image
        run: docker push hegemonies/hegemonies.site:latest
      - name: deploy to prod
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOSTNAME }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: ./deploy-hegemonies-site-v4.sh
