name: deploy to production

on: [push]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3
      - name: build docker image
        run: docker build --tag hegemonies/hegemonies.site:latest .
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: push docker image
        run: docker push hegemonies/hegemonies.site:latest
      - name: deploy to prod
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOSTNAME }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: ./deploy-hegemonies-site-v4.sh
